language: python
branches:
  only:
    - master
    - development
python:
  - "3.6"
services:
  - postgresql
addons:
  postgresql: "9.6"
install:
  - pip3 install -r requirements.txt
before_script:
  - yes | ./setup.sh
script:
  - python3 -m unittest discover -s app
